# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2ef2aa25fc0ccc91d44a7277fceda46a606ec1a817430e7c7cd54c3d5a01107aa5a6f386b096599eece5f3cd23cebe8f5e288fc58fa981c7cbd864611a60cca5

test:
  secret_key_base: 9bbece17ef2be7770e12252925949f79adc74a1459e5251f4431903d8e17d82cc6f3ed8494df5a7ec814d26e61e650c9b6089a5d2ac8f11b7e926e658c5fea25

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
